/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AdventOfCode2015;

import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.security.NoSuchAlgorithmException;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class AdventOfCode2015Test {

    @Test
    void _01_01() throws IOException, URISyntaxException {

        final var input = Files.readString(Paths.get(getClass().getResource("/01").toURI()));

        final var answer = AdventOfCode2015._01_01(input);

        Assertions.assertEquals(74, answer);

    }

    @Test
    void _01_02() throws IOException, URISyntaxException {

        final var input = Files.readString(Paths.get(getClass().getResource("/01").toURI()));

        final var answer = AdventOfCode2015._01_02(input);

        Assertions.assertEquals(1795, answer);

    }

    @Test
    void _02_01() throws IOException, URISyntaxException {

        final var input = Files.readAllLines(Paths.get(getClass().getResource("/02").toURI()));

        final var answer = AdventOfCode2015._02_01(input);

        Assertions.assertEquals(1606483, answer);

    }

    @Test
    void _02_02() throws IOException, URISyntaxException {

        final var input = Files.readAllLines(Paths.get(getClass().getResource("/02").toURI()));

        final var answer = AdventOfCode2015._02_02(input);

        System.out.println(answer);

        Assertions.assertEquals(3842356, answer);

    }

    @Test
    void _03_01() throws IOException, URISyntaxException {

        final var input = Files.readString(Paths.get(getClass().getResource("/03").toURI()));

        final var answer = AdventOfCode2015._03_01(input);

        Assertions.assertEquals(2565, answer);

    }

    @Test
    void _03_02() throws IOException, URISyntaxException {

        final var input = Files.readString(Paths.get(getClass().getResource("/03").toURI()));

        final var answer = AdventOfCode2015._03_02(input);

        System.out.println(answer);

        Assertions.assertEquals(2639, answer);

    }

    @Test
    void _04_01() throws IOException, URISyntaxException, NoSuchAlgorithmException {

        final var input = Files.readString(Paths.get(getClass().getResource("/04").toURI()));

        final var answer = AdventOfCode2015._04_01(input);

        Assertions.assertEquals(282749, answer);

    }

    @Test
    void _04_02() throws IOException, URISyntaxException, NoSuchAlgorithmException {

        final var input = Files.readString(Paths.get(getClass().getResource("/04").toURI()));

        final var answer = AdventOfCode2015._04_02(input);

        Assertions.assertEquals(9962624, answer);

    }

}
